### ISSUE TITLE
Can We Release the Original Training Data?

### ISSUE THREAD

**Issue by YuboFeng2023** [gaojun4ever/SWCC4Event#1]
Hi, 

I love this fabulous work! 

I am very interested in this work and event representation, and I want to follow your research.
 
So can you release the Original Training Data, which is New York Times Gigaword Corpus, and Extraction results?

Best wishes!

**Comment by ccclyu** [comment]
The original corpus New York Times Gigaword is not supposed to be distributed. Please follow the instruction [https://catalog.ldc.upenn.edu/LDC2003T05](url) to access the original corpus.

**Comment by YuboFeng2023** [comment]
> 

Thanks for your helpful reply !
